version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - php
      - db
    volumes:
      - ./web/html:/var/www/html
      - ./web/logs:/var/log/nginx
    networks:
      - lamp-network

  php:
    build: ./php
    volumes:
      - ./web/html:/var/www/html
    networks:
      - lamp-network

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mydatabase" 
      MYSQL_USER: "user" 
      MYSQL_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

networks:
  lamp-network:

volumes:
  db_data: {}